clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: media_avportal

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
    - COMPOSERVER=--2
    - DOCUMENT_ROOT=/test/media_avportal
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-4.1.3-20220405
    shm_size: 2g
    environment:
    - DISPLAY=:99
    - SCREEN_WIDTH=1280
    - SCREEN_HEIGHT=800
    - NODE_MAX_INSTANCES=5
    - NODE_MAX_SESSION=5

pipeline:
  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    commands:
      - composer self-update --2
      - composer require drupal/core:~${CORE_VERSION} drupal/core-composer-scaffold:~${CORE_VERSION} drupal/core-dev:~${CORE_VERSION} --update-with-all-dependencies --ansi --no-progress --no-interaction

  site-install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - while ! mysqladmin ping -h mysql --silent; do sleep 1; done
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit

matrix:
  include:
    - CORE_VERSION: 10.1.0
      PHP_VERSION: 8.1
    - CORE_VERSION: 10.1.0
      PHP_VERSION: 8.2
    - CORE_VERSION: 10.2.0
      PHP_VERSION: 8.1
    - CORE_VERSION: 10.2.0
      PHP_VERSION: 8.2
